In [ ]:
from google.colab import drive    #For drive Mounting
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import math

## **Data preprocessing:**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
target="Sleep Stage"

In [ ]:
dataset[target].value_counts()

NREM    1798
Wake     629
REM      573
Name: Sleep Stage, dtype: int64

## **Data Reading:**

In [ ]:
dataset=pd.read_csv('/content/drive/MyDrive/Machine Learning/Sleep_data/EEG_HMC_Wake_NREM_REM_3000.csv')

In [ ]:
dataset.head(10)

,Sleep Stage,MeanP_Alpha_F4,MedianF_Alpha_F4,MeanF_Alpha_F4,Spectral Edge_Alpha_F4,PeakF_Alpha_F4,MeanP_Beta_F4,MedianF_Beta_F4,MeanF_Beta_F4,Spectral Edge_Beta_F4,...,MeanP_Delta_O2,MedianF_Delta_O2,MeanF_Delta_O2,Spectral Edge_Delta_O2,PeakF_Delta_O2,MeanP_Gamma_O2,MedianF_Gamma_O2,MeanF_Gamma_O2,Spectral Edge_Gamma_O2,PeakF_Gamma_O2
0,Wake,0.00051,8.74146,18.48195,17.48293,8.24195,0.00071,19.73073,29.84585,33.84195,...,0.00724,0.74927,3.87122,1.99805,0.87415,0.000210,35.21561,42.20878,49.95122,49.95122
1,Wake,0.00040,10.24000,17.48293,16.85854,10.61463,0.00051,17.23317,26.34927,29.34634,...,0.00723,0.49951,3.74634,1.24878,0.49951,0.000095,34.34146,43.33268,49.95122,49.95122
2,Wake,0.00036,9.74049,17.98244,17.48293,8.74146,0.00047,17.60780,25.47512,28.22244,...,0.00230,0.62439,5.24488,2.12293,0.62439,0.000074,34.59122,45.95512,49.95122,49.95122
3,Wake,0.00035,10.11512,17.60780,17.10829,9.61561,0.00047,17.35805,26.47415,28.72195,...,0.00091,0.87415,6.61854,3.12195,0.62439,0.000082,32.46829,43.95707,49.95122,49.95122
4,Wake,0.00033,9.74049,17.60780,17.23317,8.11707,0.00043,17.23317,25.84976,28.09756,...,0.00175,0.49951,5.74439,2.24780,0.49951,0.000077,33.59220,44.83122,49.95122,49.95122
5,Wake,0.00036,10.24000,16.98341,16.35902,10.11512,0.00043,16.35902,25.22537,27.09854,...,0.00066,1.12390,7.74244,3.49659,0.74927,0.000065,33.34244,45.95512,49.95122,49.95122
6,NREM,0.00034,10.11512,17.85756,17.48293,10.24000,0.00047,17.73268,25.35024,27.47317,...,0.00112,0.74927,6.36878,2.87220,0.62439,0.000076,32.71805,43.83220,49.95122,49.95122
7,NREM,0.00035,10.73951,17.60780,17.10829,9.11610,0.00048,16.85854,25.22537,26.97366,...,0.00070,0.99902,6.86829,3.62146,0.74927,0.000072,32.09366,44.33171,49.95122,49.95122
8,NREM,0.00035,9.36585,17.60780,16.98341,9.24098,0.00042,17.35805,26.09951,28.47220,...,0.00077,1.49854,6.49366,4.12098,0.74927,0.000069,33.09268,43.95707,49.95122,49.95122
9,NREM,0.00050,10.36488,16.60878,15.85951,7.99220,0.00053,15.48488,24.10146,25.72488,...,0.00130,1.87317,6.11902,3.74634,0.37463,0.000070,31.59415,42.83317,49.95122,49.95122

In [ ]:
dataset.tail(10)

,Sleep Stage,MeanP_Alpha_F4,MedianF_Alpha_F4,MeanF_Alpha_F4,Spectral Edge_Alpha_F4,PeakF_Alpha_F4,MeanP_Beta_F4,MedianF_Beta_F4,MeanF_Beta_F4,Spectral Edge_Beta_F4,...,MeanP_Delta_O2,MedianF_Delta_O2,MeanF_Delta_O2,Spectral Edge_Delta_O2,PeakF_Delta_O2,MeanP_Gamma_O2,MedianF_Gamma_O2,MeanF_Gamma_O2,Spectral Edge_Gamma_O2,PeakF_Gamma_O2
2990,NREM,0.00080,7.49268,12.48780,10.86439,6.61854,0.00032,9.49073,19.48098,18.85659,...,0.00461,1.24878,6.36878,3.62146,0.87415,0.000011,20.97951,36.21463,42.70829,13.61171
2991,NREM,0.00113,7.61756,11.61366,10.73951,6.61854,0.00043,9.49073,18.73171,17.98244,...,0.00801,1.12390,5.86927,2.87220,0.87415,0.000012,17.73268,34.96585,41.45951,13.23707
2992,NREM,0.00103,7.86732,11.73854,10.61463,8.24195,0.00040,9.36585,18.23220,17.48293,...,0.00602,1.24878,6.24390,3.12195,0.74927,0.000012,20.23024,35.59024,42.08390,12.98732
2993,NREM,0.00119,7.61756,11.48878,10.61463,8.11707,0.00043,8.99122,17.10829,16.23415,...,0.01136,0.87415,5.36976,2.49756,0.74927,0.000011,21.35415,35.84000,42.83317,13.11220
2994,NREM,0.00104,7.36780,11.48878,10.24000,7.24293,0.00038,8.99122,18.23220,17.35805,...,0.00653,0.99902,5.99415,2.99707,0.62439,0.000011,19.98049,35.84000,43.58244,12.61268
2995,NREM,0.00089,7.36780,12.11317,10.61463,6.74341,0.00033,9.24098,19.23122,18.73171,...,0.00970,0.99902,5.86927,2.49756,0.99902,0.000011,20.48000,36.33951,42.45854,12.86244
2996,NREM,0.00085,7.49268,11.61366,10.61463,7.99220,0.00032,9.36585,19.23122,18.35707,...,0.01049,1.12390,5.12000,2.62244,0.87415,0.000009,22.85268,37.21366,44.08195,13.36195
2997,NREM,0.00097,7.36780,11.48878,10.61463,7.36780,0.00036,9.49073,18.23220,17.35805,...,0.00759,1.24878,5.86927,2.74732,0.74927,0.000011,20.48000,35.59024,42.08390,12.61268
2998,NREM,0.00110,7.49268,11.23902,10.61463,8.86634,0.00040,9.24098,17.23317,16.35902,...,0.00753,0.99902,5.74439,2.87220,0.99902,0.000010,20.72976,36.08976,43.45756,12.86244
2999,NREM,0.00101,7.36780,11.48878,10.36488,8.24195,0.00036,8.99122,18.35707,17.35805,...,0.00923,0.99902,5.86927,2.87220,0.99902,0.000011,20.48000,35.96488,43.20780,13.48683

In [ ]:
dataset.shape # (row, column)

(3000, 76)

In [ ]:
list(dataset.columns)

['Sleep Stage',
 'MeanP_Alpha_F4',
 'MedianF_Alpha_F4',
 'MeanF_Alpha_F4',
 'Spectral Edge_Alpha_F4',
 'PeakF_Alpha_F4',
 'MeanP_Beta_F4',
 'MedianF_Beta_F4',
 'MeanF_Beta_F4',
 'Spectral Edge_Beta_F4',
 'PeakF_Beta_F4',
 'MeanP_Theta_F4',
 'MedianF_Theta_F4',
 'MeanF_Theta_F4',
 'Spectral Edge_Theta_F4',
 'PeakF_Theta_F4',
 'MeanP_Delta_F4',
 'MedianF_Delta_F4',
 'MeanF_Delta_F4',
 'Spectral Edge_Delta_F4',
 'PeakF_Delta_F4',
 'MeanP_Gamma_F4',
 'MedianF_Gamma_F4',
 'MeanF_Gamma_F4',
 'Spectral Edge_Gamma_F4',
 'PeakF_Gamma_F4',
 'MeanP_Alpha_C4',
 'MedianF_Alpha_C4',
 'MeanF_Alpha_C4',
 'Spectral Edge_Alpha_C4',
 'PeakF_Alpha_C4',
 'MeanP_Beta_C4',
 'MedianF_Beta_C4',
 'MeanF_Beta_C4',
 'Spectral Edge_Beta_C4',
 'PeakF_Beta_C4',
 'MeanP_Theta_C4',
 'MedianF_Theta_C4',
 'MeanF_Theta_C4',
 'Spectral Edge_Theta_C4',
 'PeakF_Theta_C4',
 'MeanP_Delta_C4',
 'MedianF_Delta_C4',
 'MeanF_Delta_C4',
 'Spectral Edge_Delta_C4',
 'PeakF_Delta_C4',
 'MeanP_Gamma_C4',
 'MedianF_Gamma_C4',
 'MeanF_Gamma_C4',
 'Spectral Edge_Gamma_C4',
 'PeakF_Gamma_C4',
 'MeanP_Alpha_O2',
 'MedianF_Alpha_O2',
 'MeanF_Alpha_O2',
 'Spectral Edge_Alpha_O2',
 'PeakF_Alpha_O2',
 'MeanP_Beta_O2',
 'MedianF_Beta_O2',
 'MeanF_Beta_O2',
 'Spectral Edge_Beta_O2',
 'PeakF_Beta_O2',
 'MeanP_Theta_O2',
 'MedianF_Theta_O2',
 'MeanF_Theta_O2',
 'Spectral Edge_Theta_O2',
 'PeakF_Theta_O2',
 'MeanP_Delta_O2',
 'MedianF_Delta_O2',
 'MeanF_Delta_O2',
 'Spectral Edge_Delta_O2',
 'PeakF_Delta_O2',
 'MeanP_Gamma_O2',
 'MedianF_Gamma_O2',
 'MeanF_Gamma_O2',
 'Spectral Edge_Gamma_O2',
 'PeakF_Gamma_O2']

In [ ]:
dataset.info() # showes the datatype of all data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 76 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sleep Stage             3000 non-null   object
 1   MeanP_Alpha_F4          3000 non-null   float64
 2   MedianF_Alpha_F4        3000 non-null   float64
 3   MeanF_Alpha_F4          3000 non-null   float64
 4   Spectral Edge_Alpha_F4  3000 non-null   float64
 5   PeakF_Alpha_F4          3000 non-null   float64
 6   MeanP_Beta_F4           3000 non-null   float64
 7   MedianF_Beta_F4         3000 non-null   float64
 8   MeanF_Beta_F4           3000 non-null   float64
 9   Spectral Edge_Beta_F4   3000 non-null   float64
 10  PeakF_Beta_F4           3000 non-null   float64
 11  MeanP_Theta_F4          3000 non-null   float64
 12  MedianF_Theta_F4        3000 non-null   float64
 13  MeanF_Theta_F4          3000 non-null   float64
 14  Spectral Edge_Theta_F4  3000 non-null   float64
 15  PeakF_Theta_F4          3000 non-null   float64
 16  MeanP_Delta_F4          3000 non-null   float64
 17  MedianF_Delta_F4        3000 non-null   float64
 18  MeanF_Delta_F4          3000 non-null   float64
 19  Spectral Edge_Delta_F4  3000 non-null   float64
 20  PeakF_Delta_F4          3000 non-null   float64
 21  MeanP_Gamma_F4          3000 non-null   float64
 22  MedianF_Gamma_F4        3000 non-null   float64
 23  MeanF_Gamma_F4          3000 non-null   float64
 24  Spectral Edge_Gamma_F4  3000 non-null   float64
 25  PeakF_Gamma_F4          3000 non-null   float64
 26  MeanP_Alpha_C4          3000 non-null   float64
 27  MedianF_Alpha_C4        3000 non-null   float64
 28  MeanF_Alpha_C4          3000 non-null   float64
 29  Spectral Edge_Alpha_C4  3000 non-null   float64
 30  PeakF_Alpha_C4          3000 non-null   float64
 31  MeanP_Beta_C4           3000 non-null   float64
 32  MedianF_Beta_C4         3000 non-null   float64
 33  MeanF_Beta_C4           3000 non-null   float64
 34  Spectral Edge_Beta_C4   3000 non-null   float64
 35  PeakF_Beta_C4           3000 non-null   float64
 36  MeanP_Theta_C4          3000 non-null   float64
 37  MedianF_Theta_C4        3000 non-null   float64
 38  MeanF_Theta_C4          3000 non-null   float64
 39  Spectral Edge_Theta_C4  3000 non-null   float64
 40  PeakF_Theta_C4          3000 non-null   float64
 41  MeanP_Delta_C4          3000 non-null   float64
 42  MedianF_Delta_C4        3000 non-null   float64
 43  MeanF_Delta_C4          3000 non-null   float64
 44  Spectral Edge_Delta_C4  3000 non-null   float64
 45  PeakF_Delta_C4          3000 non-null   float64
 46  MeanP_Gamma_C4          3000 non-null   float64
 47  MedianF_Gamma_C4        3000 non-null   float64
 48  MeanF_Gamma_C4          3000 non-null   float64
 49  Spectral Edge_Gamma_C4  3000 non-null   float64
 50  PeakF_Gamma_C4          3000 non-null   float64
 51  MeanP_Alpha_O2          3000 non-null   float64
 52  MedianF_Alpha_O2        3000 non-null   float64
 53  MeanF_Alpha_O2          3000 non-null   float64
 54  Spectral Edge_Alpha_O2  3000 non-null   float64
 55  PeakF_Alpha_O2          3000 non-null   float64
 56  MeanP_Beta_O2           3000 non-null   float64
 57  MedianF_Beta_O2         3000 non-null   float64
 58  MeanF_Beta_O2           3000 non-null   float64
 59  Spectral Edge_Beta_O2   3000 non-null   float64
 60  PeakF_Beta_O2           3000 non-null   float64
 61  MeanP_Theta_O2          3000 non-null   float64
 62  MedianF_Theta_O2        3000 non-null   float64
 63  MeanF_Theta_O2          3000 non-null   float64
 64  Spectral Edge_Theta_O2  3000 non-null   float64
 65  PeakF_Theta_O2          3000 non-null   float64
 66  MeanP_Delta_O2          3000 non-null   float64
 67  MedianF_Delta_O2        3000 non-null   float64
 68  MeanF_Delta_O2          3000 non-null   float64
 69  Spectral Edge_Delta_O2  3000 non-null   float64
 70  PeakF_Delta_O2          3000 non-null   float64
 71  MeanP_Gamma_O2          3000 non-null   float64
 72  MedianF_Gamma_O2        3000 non-null   float64
 73  MeanF_Gamma_O2          3000 non-null   float64
 74  Spectral Edge_Gamma_O2  3000 non-null   float64
 75  PeakF_Gamma_O2          3000 non-null   float64
dtypes: float64(75), object(1)
memory usage: 1.7+ MB

In [ ]:
dataset.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,366.000000,366.000000,366.000000,366.000000,363.000000,364.000000,359.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000
mean,7.265574,20.550273,1.428415,4.521858,7.909366,39.840659,9.651811,17.986339,72.035519,44.519126,1019.709016,1016.810383,3.890710,4.024590,12.358470,19.230874,1.428415
std,6.025800,6.690516,4.225800,2.669383,3.481517,13.059807,7.951929,8.856997,13.137058,16.850947,6.686212,6.469422,2.956131,2.666268,5.630832,6.640346,4.225800
min,-5.300000,7.600000,0.000000,0.200000,0.000000,13.000000,0.000000,0.000000,36.000000,13.000000,996.500000,996.800000,0.000000,0.000000,0.100000,5.100000,0.000000
25%,2.300000,15.025000,0.000000,2.200000,5.950000,31.000000,6.000000,11.000000,64.000000,32.250000,1015.350000,1012.800000,1.000000,1.000000,7.625000,14.150000,0.000000
50%,7.450000,19.650000,0.000000,4.200000,8.600000,39.000000,7.000000,17.000000,72.000000,43.000000,1020.150000,1017.400000,3.500000,4.000000,12.550000,18.550000,0.000000
75%,12.500000,25.500000,0.200000,6.400000,10.500000,46.000000,13.000000,24.000000,81.000000,55.000000,1024.475000,1021.475000,7.000000,7.000000,17.000000,24.000000,0.200000
max,20.900000,35.800000,39.800000,13.800000,13.600000,98.000000,41.000000,52.000000,99.000000,96.000000,1035.700000,1033.200000,8.000000,8.000000,24.700000,34.500000,39.800000

In [ ]:
dataset['WindGustDir'].unique() # showes unique values in that column

array(['NW', 'ENE', 'SSE', 'SE', 'E', 'S', 'N', 'WNW', 'ESE', 'NE', 'NNE',
       'NNW', 'SW', 'W', 'WSW', 'SSW', nan], dtype=object)

In [ ]:
dataset['WindGustDir'].value_counts() # shows the frequency of the datas of a column

NW     73
NNW    44
E      37
WNW    35
ENE    30
ESE    23
S      22
N      21
W      20
NE     16
SSE    12
SE     12
NNE     8
SSW     5
SW      3
WSW     2
Name: WindGustDir, dtype: int64

## **Dropping null/nan Values**

In [ ]:
dataset.dropna(axis=0, how='any', inplace = True)
dataset = dataset.reset_index(drop=True)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 76 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sleep Stage             3000 non-null   object
 1   MeanP_Alpha_F4          3000 non-null   float64
 2   MedianF_Alpha_F4        3000 non-null   float64
 3   MeanF_Alpha_F4          3000 non-null   float64
 4   Spectral Edge_Alpha_F4  3000 non-null   float64
 5   PeakF_Alpha_F4          3000 non-null   float64
 6   MeanP_Beta_F4           3000 non-null   float64
 7   MedianF_Beta_F4         3000 non-null   float64
 8   MeanF_Beta_F4           3000 non-null   float64
 9   Spectral Edge_Beta_F4   3000 non-null   float64
 10  PeakF_Beta_F4           3000 non-null   float64
 11  MeanP_Theta_F4          3000 non-null   float64
 12  MedianF_Theta_F4        3000 non-null   float64
 13  MeanF_Theta_F4          3000 non-null   float64
 14  Spectral Edge_Theta_F4  3000 non-null   float64
 15  PeakF_Theta_F4          3000 non-null   float64
 16  MeanP_Delta_F4          3000 non-null   float64
 17  MedianF_Delta_F4        3000 non-null   float64
 18  MeanF_Delta_F4          3000 non-null   float64
 19  Spectral Edge_Delta_F4  3000 non-null   float64
 20  PeakF_Delta_F4          3000 non-null   float64
 21  MeanP_Gamma_F4          3000 non-null   float64
 22  MedianF_Gamma_F4        3000 non-null   float64
 23  MeanF_Gamma_F4          3000 non-null   float64
 24  Spectral Edge_Gamma_F4  3000 non-null   float64
 25  PeakF_Gamma_F4          3000 non-null   float64
 26  MeanP_Alpha_C4          3000 non-null   float64
 27  MedianF_Alpha_C4        3000 non-null   float64
 28  MeanF_Alpha_C4          3000 non-null   float64
 29  Spectral Edge_Alpha_C4  3000 non-null   float64
 30  PeakF_Alpha_C4          3000 non-null   float64
 31  MeanP_Beta_C4           3000 non-null   float64
 32  MedianF_Beta_C4         3000 non-null   float64
 33  MeanF_Beta_C4           3000 non-null   float64
 34  Spectral Edge_Beta_C4   3000 non-null   float64
 35  PeakF_Beta_C4           3000 non-null   float64
 36  MeanP_Theta_C4          3000 non-null   float64
 37  MedianF_Theta_C4        3000 non-null   float64
 38  MeanF_Theta_C4          3000 non-null   float64
 39  Spectral Edge_Theta_C4  3000 non-null   float64
 40  PeakF_Theta_C4          3000 non-null   float64
 41  MeanP_Delta_C4          3000 non-null   float64
 42  MedianF_Delta_C4        3000 non-null   float64
 43  MeanF_Delta_C4          3000 non-null   float64
 44  Spectral Edge_Delta_C4  3000 non-null   float64
 45  PeakF_Delta_C4          3000 non-null   float64
 46  MeanP_Gamma_C4          3000 non-null   float64
 47  MedianF_Gamma_C4        3000 non-null   float64
 48  MeanF_Gamma_C4          3000 non-null   float64
 49  Spectral Edge_Gamma_C4  3000 non-null   float64
 50  PeakF_Gamma_C4          3000 non-null   float64
 51  MeanP_Alpha_O2          3000 non-null   float64
 52  MedianF_Alpha_O2        3000 non-null   float64
 53  MeanF_Alpha_O2          3000 non-null   float64
 54  Spectral Edge_Alpha_O2  3000 non-null   float64
 55  PeakF_Alpha_O2          3000 non-null   float64
 56  MeanP_Beta_O2           3000 non-null   float64
 57  MedianF_Beta_O2         3000 non-null   float64
 58  MeanF_Beta_O2           3000 non-null   float64
 59  Spectral Edge_Beta_O2   3000 non-null   float64
 60  PeakF_Beta_O2           3000 non-null   float64
 61  MeanP_Theta_O2          3000 non-null   float64
 62  MedianF_Theta_O2        3000 non-null   float64
 63  MeanF_Theta_O2          3000 non-null   float64
 64  Spectral Edge_Theta_O2  3000 non-null   float64
 65  PeakF_Theta_O2          3000 non-null   float64
 66  MeanP_Delta_O2          3000 non-null   float64
 67  MedianF_Delta_O2        3000 non-null   float64
 68  MeanF_Delta_O2          3000 non-null   float64
 69  Spectral Edge_Delta_O2  3000 non-null   float64
 70  PeakF_Delta_O2          3000 non-null   float64
 71  MeanP_Gamma_O2          3000 non-null   float64
 72  MedianF_Gamma_O2        3000 non-null   float64
 73  MeanF_Gamma_O2          3000 non-null   float64
 74  Spectral Edge_Gamma_O2  3000 non-null   float64
 75  PeakF_Gamma_O2          3000 non-null   float64
dtypes: float64(75), object(1)
memory usage: 1.7+ MB

## **Label Encoding**

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

In [ ]:
dataset[target].value_counts()

NREM    1798
Wake     629
REM      573
Name: Sleep Stage, dtype: int64

In [ ]:
dataset[target]=encoder.fit_transform(dataset[target])

In [ ]:
dataset[target].value_counts()

0    1798
2     629
1     573
Name: Sleep Stage, dtype: int64

### **PreProcessing:**

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

dataset['WindGustDir'] = encoder.fit_transform(dataset['WindGustDir'])
dataset['WindDir9am'] = encoder.fit_transform(dataset['WindDir9am'])
dataset['WindDir3pm'] = encoder.fit_transform(dataset['WindDir3pm'])
dataset['RainToday'] = encoder.fit_transform(dataset['RainToday'])
dataset['RainTomorrow'] = encoder.fit_transform(dataset['RainTomorrow'])

In [ ]:
dataset.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,7,30.0,12,7,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,0,3.6,1
1,14.0,26.9,3.6,4.4,9.7,1,39.0,0,13,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,1,3.6,1
2,13.7,23.4,3.6,5.8,3.3,7,85.0,3,5,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,1,39.8,1
3,13.3,15.5,39.8,7.2,9.1,7,54.0,14,13,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,1,2.8,1
4,7.6,16.1,2.8,5.6,10.6,10,50.0,10,2,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,1,0.0,0

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 328 entries, 0 to 327
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MinTemp        328 non-null    float64
 1   MaxTemp        328 non-null    float64
 2   Rainfall       328 non-null    float64
 3   Evaporation    328 non-null    float64
 4   Sunshine       328 non-null    float64
 5   WindGustDir    328 non-null    int64
 6   WindGustSpeed  328 non-null    float64
 7   WindDir9am     328 non-null    int64
 8   WindDir3pm     328 non-null    int64
 9   WindSpeed9am   328 non-null    float64
 10  WindSpeed3pm   328 non-null    int64
 11  Humidity9am    328 non-null    int64
 12  Humidity3pm    328 non-null    int64
 13  Pressure9am    328 non-null    float64
 14  Pressure3pm    328 non-null    float64
 15  Cloud9am       328 non-null    int64
 16  Cloud3pm       328 non-null    int64
 17  Temp9am        328 non-null    float64
 18  Temp3pm        328 non-null    float64
 19  RainToday      328 non-null    int64
 20  RISK_MM        328 non-null    float64
 21  RainTomorrow   328 non-null    int64
dtypes: float64(12), int64(10)
memory usage: 56.5 KB

## **Data Spliting:**

Loc-> Location

df.loc[starting_row : ending_row,[column]]

iloc->index location
df.loc[starting_row:ending_row,starting_col:ending_col+1}

In [108]:
x=dataset.loc[:,dataset.columns!=target]

In [109]:
x.head()

,MeanP_Alpha_F4,MedianF_Alpha_F4,MeanF_Alpha_F4,Spectral Edge_Alpha_F4,PeakF_Alpha_F4,MeanP_Beta_F4,MedianF_Beta_F4,MeanF_Beta_F4,Spectral Edge_Beta_F4,PeakF_Beta_F4,...,MeanP_Delta_O2,MedianF_Delta_O2,MeanF_Delta_O2,Spectral Edge_Delta_O2,PeakF_Delta_O2,MeanP_Gamma_O2,MedianF_Gamma_O2,MeanF_Gamma_O2,Spectral Edge_Gamma_O2,PeakF_Gamma_O2
0,0.00051,8.74146,18.48195,17.48293,8.24195,0.00071,19.73073,29.84585,33.84195,15.98439,...,0.00724,0.74927,3.87122,1.99805,0.87415,0.000210,35.21561,42.20878,49.95122,49.95122
1,0.00040,10.24000,17.48293,16.85854,10.61463,0.00051,17.23317,26.34927,29.34634,19.60585,...,0.00723,0.49951,3.74634,1.24878,0.49951,0.000095,34.34146,43.33268,49.95122,49.95122
2,0.00036,9.74049,17.98244,17.48293,8.74146,0.00047,17.60780,25.47512,28.22244,18.73171,...,0.00230,0.62439,5.24488,2.12293,0.62439,0.000074,34.59122,45.95512,49.95122,49.95122
3,0.00035,10.11512,17.60780,17.10829,9.61561,0.00047,17.35805,26.47415,28.72195,16.35902,...,0.00091,0.87415,6.61854,3.12195,0.62439,0.000082,32.46829,43.95707,49.95122,49.95122
4,0.00033,9.74049,17.60780,17.23317,8.11707,0.00043,17.23317,25.84976,28.09756,17.60780,...,0.00175,0.49951,5.74439,2.24780,0.49951,0.000077,33.59220,44.83122,49.95122,49.95122

In [110]:
y=dataset[target]

In [111]:
y.head()

0    2
1    2
2    2
3    2
4    2
Name: Sleep Stage, dtype: int64

## **Dataset spliting in testing and training**

In [112]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.2)

## **Training Phase**

## **RandomForestt**

In [113]:
%%time

from sklearn.ensemble import RandomForestClassifier   #importing libraries

clf = RandomForestClassifier()                        #creating method of algorithm 
                                                      #(Bracket a kichu na dile Default Parameter nibe)
                                                      #1st time model banaile default parameter newa valo
                                                      
clf.fit(x_train, y_train)                             #model fitting / data feeding / training

y_pred=clf.predict(x_test)                            #prediction

CPU times: user 1.33 s, sys: 0 ns, total: 1.33 s
Wall time: 1.37 s

In [114]:
from sklearn.metrics import accuracy_score

score=accuracy_score(y_test,y_pred)

print(score)

0.9266666666666666

In [ ]:
rain_tom=clf.predict(x.loc[101:101,:])
print(rain_tom)

[0]

In [ ]:
y[101]

0

**Model save**

In [ ]:
import joblib
joblib.dump(clf,"randomfores_rain_tom")

['randomfores_rain_tom']

adaboost

GradientBossting

KNN

Naive Byes

## **AdaBoost**

In [119]:
from sklearn.ensemble import AdaBoostClassifier         #importing libraries


ada = AdaBoostClassifier()                              #creating method of algorithm 
                                                        #(Bracket a kichu na dile Default Parameter nibe)
                                                        #1st time model banaile default parameter newa valo

ada.fit(x_train, y_train)                               #model fitting / data feeding / training


y_pred = ada.predict(x_test)                                     #prediction



#clf.score(x, y)

In [120]:
from sklearn.metrics import accuracy_score

score=accuracy_score(y_test,y_pred)

print(score)

0.79

## **GradientBoosting**

In [115]:
from sklearn.datasets import make_hastie_10_2
from sklearn.ensemble import GradientBoostingClassifier

GB = GradientBoostingClassifier()
GB.fit(x_train, y_train)

y_pred = GB.predict(x_test)

In [116]:
from sklearn.metrics import accuracy_score

score=accuracy_score(y_test,y_pred)

print(score)

0.9366666666666666

## **KNN**

In [121]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier()

neigh.fit(x_train, y_train)

y_pred =neigh.predict(x_test)

In [122]:
from sklearn.metrics import accuracy_score

score=accuracy_score(y_test,y_pred)

print(score)

0.8983333333333333

## **Naive Byes**

In [123]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(x_train,y_train)

y_pred = gnb.predict(x_test)

In [124]:
from sklearn.metrics import accuracy_score

score=accuracy_score(y_test,y_pred)

print(score)

0.705